#include "Renderer/DX12/GraphicsPipeline.h"
#include "Core/Logger.h"

namespace SGE {

bool GraphicsPipeline::Create(ID3D12Device* device, const GraphicsPipelineDesc& desc)
{
    m_desc = desc;
    return BuildPSO(device);
}

void GraphicsPipeline::UpdateShaders(std::shared_ptr<ShaderBlob> vs, std::shared_ptr<ShaderBlob> ps)
{
    m_desc.vs = std::move(vs);
    m_desc.ps = std::move(ps);
}

bool GraphicsPipeline::Rebuild(ID3D12Device* device)
{
    m_pso.Reset();
    return BuildPSO(device);
}

bool GraphicsPipeline::BuildPSO(ID3D12Device* device)
{
    try {
        D3D12_GRAPHICS_PIPELINE_STATE_DESC psoDesc = {};
        psoDesc.pRootSignature = m_desc.rootSignature;
        psoDesc.VS             = m_desc.vs->GetBytecode();
        if (m_desc.ps) psoDesc.PS = m_desc.ps->GetBytecode(); // null PS => depth-only (shadow pass)
        // Optional tessellation stages (between VS and the rasterizer).
        if (m_desc.hs) psoDesc.HS = m_desc.hs->GetBytecode();
        if (m_desc.ds) psoDesc.DS = m_desc.ds->GetBytecode();

        // Input layout is auto-generated by DxcInstance from VS reflection.
        psoDesc.InputLayout.pInputElementDescs = m_desc.vs->inputLayout.data();
        psoDesc.InputLayout.NumElements        = static_cast<UINT>(m_desc.vs->inputLayout.size());

        psoDesc.RasterizerState.FillMode              = m_desc.wireframe ? D3D12_FILL_MODE_WIREFRAME : D3D12_FILL_MODE_SOLID;
        psoDesc.RasterizerState.CullMode              = m_desc.cullMode;
        psoDesc.RasterizerState.FrontCounterClockwise = FALSE;
        psoDesc.RasterizerState.DepthClipEnable       = TRUE;

        psoDesc.DepthStencilState.DepthEnable    = m_desc.depthEnable ? TRUE : FALSE;
        psoDesc.DepthStencilState.DepthWriteMask = D3D12_DEPTH_WRITE_MASK_ALL;
        psoDesc.DepthStencilState.DepthFunc      = D3D12_COMPARISON_FUNC_LESS;
        psoDesc.DepthStencilState.StencilEnable  = FALSE;
        psoDesc.DSVFormat                        = m_desc.depthEnable ? m_desc.dsvFormat : DXGI_FORMAT_UNKNOWN;

        psoDesc.SampleMask            = UINT_MAX;
        psoDesc.PrimitiveTopologyType = m_desc.topologyType; // PATCH for tessellation
        psoDesc.SampleDesc.Count      = 1;

        // Render targets: a single-RT pipeline uses rtvFormat; the deferred geometry
        // pass sets rtvCount/rtvFormats for its MRT G-buffer; rtvCount == 0 is a
        // depth-only pass (shadow map) — no colour targets at all.
        psoDesc.NumRenderTargets = m_desc.rtvCount;
        for (uint32_t i = 0; i < m_desc.rtvCount; ++i) {
            psoDesc.RTVFormats[i] = (m_desc.rtvCount <= 1) ? m_desc.rtvFormat : m_desc.rtvFormats[i];
            psoDesc.BlendState.RenderTarget[i].RenderTargetWriteMask = D3D12_COLOR_WRITE_ENABLE_ALL;
        }

        SGE_THROW_IF_FAILED(device->CreateGraphicsPipelineState(&psoDesc, IID_PPV_ARGS(&m_pso)));

        LogInfo("Graphics pipeline built.");
        return true;
    }
    catch (const std::exception& e) {
        LogError(e.what());
        return false;
    }
}

} // namespace SGE
